<?php
/**
 * Plugin Name: P2 Next
 * Plugin URI:  https://github.com/georgestephanis/p2-next
 * Description: Modern P2/o2 replacement using the Block Editor and REST API.
 * Version:     0.1.0
 * Author:      George Stephanis
 * License:     GPL-2.0-or-later
 * Text Domain: p2-next
 *
 * @package P2Next
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'P2NEXT_VERSION', '0.1.0' );
define( 'P2NEXT_DIR', plugin_dir_path( __FILE__ ) );
define( 'P2NEXT_URL', plugin_dir_url( __FILE__ ) );

/**
 * Register the new-post FSE block.
 *
 * Uses the block manifest generated by @wordpress/scripts for efficient
 * metadata loading, then registers the block from the build directory.
 */
function p2next_register_blocks() {
	$manifest = P2NEXT_DIR . 'build/blocks-manifest.php';
	if ( file_exists( $manifest ) ) {
		wp_register_block_metadata_collection( P2NEXT_DIR . 'build', $manifest );
	}
	register_block_type( P2NEXT_DIR . 'build/blocks/new-post' );
}
add_action( 'init', 'p2next_register_blocks' );

/**
 * Enqueue the frontend enhancement script on all public pages.
 *
 * This script progressively enhances whatever post list the theme renders
 * (Query Loop block or classic loop) with live polling, inline comments,
 * and inline post editing — without replacing the theme's own output.
 */
function p2next_enqueue_frontend() {
	$asset_file = P2NEXT_DIR . 'build/frontend.asset.php';
	if ( ! file_exists( $asset_file ) ) {
		return;
	}
	$asset = require $asset_file;

	// Enqueue WordPress editor/components CSS that frontend components depend on.
	// These provide the base styles for buttons, inputs, blocks, layouts, etc.
	wp_enqueue_style( 'wp-components' );
	wp_enqueue_style( 'wp-block-editor' );
	wp_enqueue_style( 'wp-block-library' );

	// Enqueue the compiled custom styles (p2-next-specific layouts and containers).
	wp_enqueue_style(
		'p2-next-frontend',
		P2NEXT_URL . 'build/frontend.css',
		array( 'wp-components', 'wp-block-editor', 'wp-block-library' ),
		$asset['version']
	);

	wp_enqueue_script(
		'p2-next-frontend',
		P2NEXT_URL . 'build/frontend.js',
		$asset['dependencies'],
		$asset['version'],
		array( 'strategy' => 'defer' )
	);

	$current_user = wp_get_current_user();
	$user_data    = null;

	if ( $current_user->ID ) {
		$user_data = array(
			'id'         => $current_user->ID,
			'name'       => $current_user->display_name,
			'avatar'     => get_avatar_url( $current_user->ID, array( 'size' => 48 ) ),
			'canPublish' => current_user_can( 'publish_posts' ),
			'canComment' => current_user_can( 'edit_posts' ) || get_option( 'comment_registration' ) === '0',
		);
	}

	wp_add_inline_script(
		'p2-next-frontend',
		'window.p2NextConfig = ' . wp_json_encode(
			array(
				'nonce'       => wp_create_nonce( 'wp_rest' ),
				'restUrl'     => esc_url_raw( rest_url() ),
				'siteTitle'   => get_bloginfo( 'name' ),
				'currentUser' => $user_data,
				'threadDepth' => (int) get_option( 'thread_comments_depth', 5 ),
			)
		) . ';',
		'before'
	);
}
add_action( 'wp_enqueue_scripts', 'p2next_enqueue_frontend' );

/**
 * Auto-generate post title from the first line of content when none is provided.
 * Mirrors o2 behaviour for status-style posts.
 *
 * @param stdClass        $prepared_post Prepared post data.
 * @param WP_REST_Request $request       REST request.
 * @return stdClass
 */
function p2next_auto_title( $prepared_post, $request ) { // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed
	if ( empty( $prepared_post->post_title ) && ! empty( $prepared_post->post_content ) ) {
		$first_line                = strtok( wp_strip_all_tags( $prepared_post->post_content ), "\n" );
		$prepared_post->post_title = wp_trim_words( $first_line, 10, '' );
	}
	return $prepared_post;
}
add_filter( 'rest_pre_insert_post', 'p2next_auto_title', 10, 2 );
