<?php
/**
 * Plugin Name: P2026
 * Plugin URI:  https://github.com/georgestephanis/p2026
 * Update URI:  https://github.com/georgestephanis/p2026
 * Description: Modern P2/o2 replacement using the Block Editor and REST API.
 * Version:     0.4.0
 * Author:      George Stephanis
 * License:     GPL-2.0-or-later
 * Text Domain: p2026
 *
 * @package P2026
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'P2026_VERSION', '0.4.0' );
define( 'P2026_DIR', plugin_dir_path( __FILE__ ) );
define( 'P2026_URL', plugin_dir_url( __FILE__ ) );

// Abilities API registration and permission helpers.
require_once P2026_DIR . 'includes/abilities.php';

// REST fields for comment/post capabilities used by the frontend UI.
require_once P2026_DIR . 'includes/api/comment-permissions.php';

/**
 * Register the new-post FSE block.
 *
 * Uses the block manifest generated by @wordpress/scripts for efficient
 * metadata loading, then registers the block from the build directory.
 */
function p2026_register_blocks() {
	$manifest = P2026_DIR . 'build/blocks-manifest.php';
	if ( file_exists( $manifest ) ) {
		wp_register_block_metadata_collection( P2026_DIR . 'build', $manifest );
	}
	register_block_type( P2026_DIR . 'build/blocks/new-post' );
	register_block_type( P2026_DIR . 'build/blocks/feed-tools' );
}
add_action( 'init', 'p2026_register_blocks' );

/**
 * Discover all available p2026 modules by scanning the modules directory.
 *
 * @return array Associative array of module slug => module dir path.
 */
function p2026_discover_modules() {
	$modules = glob( P2026_DIR . 'modules/*/index.php' );
	if ( ! $modules ) {
		return array();
	}
	$discovered = array();
	foreach ( $modules as $module_file ) {
		$slug                = basename( dirname( $module_file ) );
		$discovered[ $slug ] = dirname( $module_file );
	}
	return $discovered;
}

/**
 * Best-effort detection for whether the active theme already has sidebar support.
 *
 * @return bool
 */
function p2026_theme_has_sidebar_functionality() {
	static $result = null;

	if ( null !== $result ) {
		return $result;
	}

	// Classic themes often expose a dedicated sidebar template file.
	if ( locate_template( array( 'sidebar.php' ), false, false ) ) {
		$result = true;
		return $result;
	}

	// Common block and hybrid theme sidebar template-part locations.
	$candidates = array(
		get_stylesheet_directory() . '/parts/sidebar.html',
		get_template_directory() . '/parts/sidebar.html',
		get_stylesheet_directory() . '/block-template-parts/sidebar.html',
		get_template_directory() . '/block-template-parts/sidebar.html',
	);

	foreach ( $candidates as $candidate ) {
		if ( file_exists( $candidate ) ) {
			$result = true;
			return $result;
		}
	}

	$result = false;
	return $result;
}

/**
 * Enqueue the frontend enhancement script on all public pages.
 *
 * This script progressively enhances whatever post list the theme renders
 * (Query Loop block or classic loop) with live polling, inline comments,
 * and inline post editing — without replacing the theme's own output.
 */
function p2026_enqueue_frontend() {
	$asset_file = P2026_DIR . 'build/frontend.asset.php';
	if ( ! file_exists( $asset_file ) ) {
		return;
	}
	$asset = require $asset_file;
	$interactivity_module_asset_file = P2026_DIR . 'build/interactivity.module.asset.php';
	$can_enqueue_interactivity_module = function_exists( 'wp_register_script_module' ) && function_exists( 'wp_enqueue_script_module' ) && file_exists( $interactivity_module_asset_file );

	// Enqueue WordPress editor/components CSS that frontend components depend on.
	// These provide the base styles for buttons, inputs, blocks, layouts, etc.
	wp_enqueue_style( 'wp-components' );
	wp_enqueue_style( 'wp-block-editor' );
	wp_enqueue_style( 'wp-block-library' );

	// Enqueue the compiled custom styles (p2026-specific layouts and containers).
	wp_enqueue_style(
		'p2026-frontend',
		P2026_URL . 'build/frontend.css',
		array( 'wp-components', 'wp-block-editor', 'wp-block-library' ),
		$asset['version']
	);
	wp_style_add_data( 'p2026-frontend', 'rtl', 'replace' );

	wp_enqueue_script(
		'p2026-frontend',
		P2026_URL . 'build/frontend.js',
		$asset['dependencies'],
		$asset['version'],
		array( 'strategy' => 'defer' )
	);

	$current_user       = wp_get_current_user();
	$user_data          = null;
	$can_publish        = p2026_can_create_posts();
	$can_update_posts   = p2026_can_update_posts();
	$can_comment        = p2026_can_create_comments();
	$require_name_email = get_option( 'require_name_email' ) === '1';
	$debug_telemetry    = defined( 'WP_DEBUG' ) && WP_DEBUG;
	$is_archive_view    = is_home() || is_front_page() || is_archive() || is_search();

	if ( $current_user->ID ) {
		$user_data = array(
			'id'             => $current_user->ID,
			'name'           => $current_user->display_name,
			'avatar'         => get_avatar_url( $current_user->ID, array( 'size' => 48 ) ),
			'canPublish'     => $can_publish,
			'canUpdatePosts' => $can_update_posts,
			'canComment'     => $can_comment,
		);
	}

	wp_add_inline_script(
		'p2026-frontend',
		'window.p2026Config = ' . wp_json_encode(
			array(
				'nonce'            => wp_create_nonce( 'wp_rest' ),
				'restUrl'          => esc_url_raw( rest_url() ),
				'siteTitle'        => get_bloginfo( 'name' ),
				'isArchiveView'    => $is_archive_view,
				'debugTelemetry'   => $debug_telemetry,
				'currentUser'      => $user_data,
				'canCreatePosts'   => $can_publish,
				'canUpdatePosts'   => $can_update_posts,
				'canComment'       => $can_comment,
				'requireNameEmail' => $require_name_email,
				'threadDepth'      => (int) get_option( 'thread_comments_depth', 5 ),
				'activeModules'    => p2026_get_active_module_slugs(),
			)
		) . ';',
		'before'
	);

	if ( $can_enqueue_interactivity_module ) {
		$interactivity_module_asset = require $interactivity_module_asset_file;

		wp_register_script_module(
			'p2026/interactivity',
			P2026_URL . 'build/interactivity.module.js',
			isset( $interactivity_module_asset['dependencies'] ) ? $interactivity_module_asset['dependencies'] : array(),
			$interactivity_module_asset['version']
		);
		wp_enqueue_script_module( 'p2026/interactivity' );
	}
}
add_action( 'wp_enqueue_scripts', 'p2026_enqueue_frontend' );

/**
 * Auto-generate post title from the first line of content when none is provided.
 * Mirrors o2 behaviour for status-style posts.
 *
 * @param stdClass        $prepared_post Prepared post data.
 * @param WP_REST_Request $request       REST request.
 * @return stdClass
 */
function p2026_auto_title( $prepared_post, $request ) { // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed
	if ( empty( $prepared_post->post_title ) && ! empty( $prepared_post->post_content ) ) {
		$first_line                = strtok( wp_strip_all_tags( $prepared_post->post_content ), "\n" );
		$prepared_post->post_title = wp_trim_words( $first_line, 10, '' );
	}
	return $prepared_post;
}
add_filter( 'rest_pre_insert_post', 'p2026_auto_title', 10, 2 );

/**
 * Add a "New Post" node to the admin bar on the front-end blog index.
 *
 * Only shown to users who can create posts. The JS click handler in
 * frontend.js either scrolls to an existing new-post editor on the page
 * or opens the React modal.
 *
 * @param WP_Admin_Bar $wp_admin_bar Admin bar instance.
 */
function p2026_admin_bar_new_post( $wp_admin_bar ) {
	if ( ! is_home() && ! is_front_page() ) {
		return;
	}
	if ( ! p2026_can_create_posts() ) {
		return;
	}
	$wp_admin_bar->add_node(
		array(
			'id'    => 'p2026-new-post',
			'title' => __( 'New Post', 'p2026' ),
			'href'  => '#',
			'meta'  => array( 'class' => 'p2026-adminbar-new-post' ),
		)
	);
}
add_action( 'admin_bar_menu', 'p2026_admin_bar_new_post', 100 );

/**
 * If the GitHub updates module file exists, include it to enable update checks
 * against the GitHub repo releases API.
 */
if ( file_exists( P2026_DIR . 'includes/github-updates.php' ) ) {
	require_once P2026_DIR . 'includes/github-updates.php';
}

// ---------------------------------------------------------------------------
// Core feature APIs (REST endpoints and backend logic).
// ---------------------------------------------------------------------------

// Search API — unified search across posts and comments.
require_once P2026_DIR . 'includes/api/search.php';

// Read/Unread state tracking — per-user last activity and unread counts.
require_once P2026_DIR . 'includes/api/read-state.php';

// ---------------------------------------------------------------------------
// Modules — self-contained feature extensions loaded from modules/*/index.php.
// ---------------------------------------------------------------------------


/**
 * Return the list of explicitly disabled module slugs.
 *
 * An empty array (or unset option) means all discovered modules are active.
 * Modules are active by default; only slugs in this list are inactive.
 *
 * @return string[]
 */
function p2026_get_disabled_modules() {
	$stored = get_option( 'p2026_disabled_modules', null );
	return is_array( $stored ) ? $stored : array();
}

/**
 * Return the list of explicitly enabled module slugs.
 *
 * This is used for modules that default to inactive.
 *
 * @return string[]
 */
function p2026_get_enabled_modules() {
	$stored = get_option( 'p2026_enabled_modules', null );
	return is_array( $stored ) ? $stored : array();
}

/**
 * Whether a given module should be active by default.
 *
 * Most modules default to active. Specific modules can opt into a different
 * default state here.
 *
 * @param string $slug Module directory slug.
 * @return bool
 */
function p2026_module_default_is_active( $slug ) {
	$slug = sanitize_key( (string) $slug );

	if ( 'sidebar-shell' === $slug ) {
		// Default to active only when the current theme appears to have no sidebar.
		return ! p2026_theme_has_sidebar_functionality();
	}

	return true;
}

/**
 * Whether a given module slug is currently active.
 *
 * A module is active unless its slug appears in the explicit deny list
 * (p2026_disabled_modules option). New modules default to active.
 *
 * @param string $slug Module directory slug.
 * @return bool
 */
function p2026_is_module_active( $slug ) {
	$slug = sanitize_key( (string) $slug );

	if ( '' === $slug ) {
		return false;
	}

	$default_active = p2026_module_default_is_active( $slug );

	if ( $default_active ) {
		return ! in_array( $slug, p2026_get_disabled_modules(), true );
	}

	return in_array( $slug, p2026_get_enabled_modules(), true );
}

/**
 * Return currently active module slugs based on discovery and activation rules.
 *
 * @return string[]
 */
function p2026_get_active_module_slugs() {
	$active = array();

	foreach ( array_keys( p2026_discover_modules() ) as $slug ) {
		if ( p2026_is_module_active( $slug ) ) {
			$active[] = $slug;
		}
	}

	return $active;
}

// Load each module whose slug is in the active list (all by default).
$modules = glob( P2026_DIR . 'modules/*/index.php' );
if ( ! $modules ) {
	$modules = array();
}
foreach ( $modules as $p2026_module ) {
	if ( p2026_is_module_active( basename( dirname( $p2026_module ) ) ) ) {
		require_once $p2026_module;
	}
}
unset( $p2026_module );

/**
 * Migrate from the legacy opt-in (p2026_active_modules) schema to the
 * current mixed-default schema.
 *
 * On first run after upgrade, the old allow-list is deleted and both the
 * explicit deny-list (p2026_disabled_modules) and explicit allow-list
 * (p2026_enabled_modules) are initialized.
 */
function p2026_migrate_module_activation_schema() {
	if ( null !== get_option( 'p2026_disabled_modules', null ) ) {
		if ( null === get_option( 'p2026_enabled_modules', null ) ) {
			update_option( 'p2026_enabled_modules', array() );
		}
		return; // Already on the new schema.
	}
	if ( null !== get_option( 'p2026_active_modules', null ) ) {
		delete_option( 'p2026_active_modules' );
	}
	update_option( 'p2026_disabled_modules', array() );
	update_option( 'p2026_enabled_modules', array() );
}
add_action( 'init', 'p2026_migrate_module_activation_schema', 1 );
// Admin settings page (menu registration, module management UI).
if ( is_admin() ) {
	require_once P2026_DIR . 'admin/settings.php';
}
